eureka :
  instance:
   client:
    serviceUrl:
     defaultZone: http://service-registry:8761
     #defaultZone: http://localhost:8761/


spring:
  application:
    name: Gateway_Service

server:
  port: 8080
