spring:
  cloud:
    gateway:
      routes:
        - id: Security_Service
          uri: lb://Security_Service
          predicates:
            - Path=/api/auth/authenticate
eureka:
  instance:
    hostname: Gateway_Service
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka
  security:
    user:
      name: mabrouka
      password: annabi
server:
  port: 8080
