app:

spring:
  application:
    name: Security_Service






  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    show-sql : true
    properties:
      hibernate:
        format_sql: true
#  Server configuration
server:
 port: 8082

  #  Eureka configuration
eureka :
  instance:
    client:
      serviceUrl:
       defaultZone: http://service-registry:8761/
